version: '3.8'

services:      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: database-name
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3
    
  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://username:password@postgres:5432/database-name?sslmode=disable
    ports:
      - 8081:8081
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      #- HTTP_USER=username
      #- HTTP_PASSWORD=password
      - PORT=8082
    ports:
      - 8082:8082
    depends_on:
      - redis
    