version: '3.8'

services:      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: database-name
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
      
  service:
    build:
      context: .
      target: test
    environment:
      - RUST_LOG=info,shine_identity=trace
      - WAIT_FOR_SERVICES=postgres.localhost.com:5432,redis.localhost.com:6379
    ports:
      - "80:80"
    links:
      - postgres:postgres.localhost.com
      - redis:redis.localhost.com
    extra_hosts:
      - mock.localhost.com:host-gateway
      - scytta-test.com:127.0.0.1
      - web.scytta-test.com:127.0.0.1
      - cloud.scytta-test.com:127.0.0.1
