version: '3.8'

services:      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: database-name
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    networks:
      my_network:
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      my_network:
      
  service:
    build:
      context: .
      target: test
    environment:
      - RUST_LOG=info,shine_identity=trace
      - WAIT_FOR_SERVICES=postgres:5432,redis:6379
    ports:
      - "80:80"
    networks:
      my_network:
    depends_on:
      - postgres
      - redis

networks:
  my_network:
    driver: bridge
