version: '3.8'

services:      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: database-name
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3
    networks:
      - shine

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - shine
      
  service:
    image: gzp79/shine-identity:test
    profiles:
      - test
    environment:
      - RUST_LOG=info,shine_identity=trace
      - WAIT_FOR_SERVICES=postgres.mock-test.com:5432,redis.mock-test.com:6379
    ports:
      - "7080:7080"
    links:
      - postgres:postgres.mock-test.com
      - redis:redis.mock-test.com
    extra_hosts:
      - mock-test.com:host-gateway
      - test.com:127.0.0.1
      - web.test.com:127.0.0.1
      - cloud.test.com:127.0.0.1
    networks:
      - shine

networks:
  shine:
    external: true
