version: '3.8'

services:      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: database-name
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3
    networks:
      - shine
    
#  pgweb:
#    image: sosedoff/pgweb
#    profiles:
#      - dev
#    depends_on:
#      - postgres
#    environment:
#      PGWEB_DATABASE_URL: postgres://username:password@postgres:5432/database-name?sslmode=disable
#    ports:
#      - 8081:8081
#    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - shine

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    profiles:
#      - dev
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#      #- HTTP_USER=username
#      #- HTTP_PASSWORD=password
#      - PORT=8082
#    ports:
#      - 8082:8082
#    depends_on:
#      - redis

  service:
    image: gzp79/shine-identity:test
    profiles:
      - test
    environment:
      - RUST_LOG=info,shine_identity=trace
      - WAIT_FOR_SERVICES=postgres.localhost.com:5432,redis.localhost.com:6379
    ports:
      - "7080:7080"
    links:
      - postgres:postgres.localhost.com
      - redis:redis.localhost.com
    extra_hosts:
      - mock.localhost.com:host-gateway
      - scytta-test.com:127.0.0.1
      - web.scytta-test.com:127.0.0.1
      - cloud.scytta-test.com:127.0.0.1
    networks:
      - shine

networks:
  shine:
    external: true
