name: Master CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# cancel outdated builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
        
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: type=sha

    - name: Start test resources
      run: |
        docker compose -f docker.yml up -d
        
    - name: Docker build
      uses: docker/build-push-action@v4
      with:
        context: .
        target: test
        push: false
        load: true
        add-hosts: |
         postgres.localhost.com:host-gateway
         redis.localhost.com:host-gateway
        # it seems as I have either host-gateway with docker driver or cache with docker-container, but not both at the same time
        #cache-from: type=gha,scope=workflow,mode=max
        #cache-to: type=gha,scope=workflow,mode=max
        tags: ${{ env.IMAGE_NAME }}:test
        
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 scytta-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 web.scytta-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 cloud.scytta-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 mock.localhost.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 postgres.localhost.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 redis.localhost.com" | sudo tee -a /etc/hosts
    - name: Integartion test
      run: |
        npm ci
        docker compose -f ../docker.yml --profile test up -d
        npm run regression
        npm run report
      working-directory: ./integration-test

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build prod
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        target: prod
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Publish Test Reports
      if: github.event_name != 'pull_request' || failure()
      uses: actions/upload-artifact@v3
      with:
        name: Test Reports
        path: | 
          ./integration-test/reports/
