name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build 
      run: docker build . --file Dockerfile --tag identity:$(date +%s)

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install
      working-directory: ./integrates-test
      
    - name: Integartion test
      run: npm run test
      working-directory: ./integrates-test
    - name: Prepare test
