name: Master CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Setup JBang
      uses: jbangdev/setup-jbang@main
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 scytta-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 web.scytta-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 cloud.scytta-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 mock.localhost.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 postgres.localhost.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 redis.localhost.com" | sudo tee -a /etc/hosts
    - run: npm ci
      working-directory: ./integration-test
    
    - name: Build 
      run: docker build . --file Dockerfile --tag identity:$(date +%s)
    - name: Integartion test
      run: npm run regression
      working-directory: ./integration-test

    - name: Test Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test Reports
        path: | 
          ./integration-test/target/karate-reports/
          ./integration-test/target/karate.log
