name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Build 
      run: docker build . --file Dockerfile --tag identity:$(date +%s)
    - run: npm install
      working-directory: ./integration-test      
    - name: Integartion test
      run: npm run regression
      working-directory: ./integration-test
