name: Master CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Build 
      run: docker build . --file Dockerfile --tag identity:$(date +%s)
    - run: npm ci
      working-directory: ./integration-test

    - name: Integartion test
      run: npm run regression
      working-directory: ./integration-test

    - name: Test Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test Reports
        path: | 
          ./integration-test/target/karate-reports/
          ./integration-test/target/karate.log
