name: Master CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# cancel outdated builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup Docker Buildx (1)
      run: |
        docker network create shine
    - name: Setup Docker Buildx (2)
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container
        driver-opts: network=shine
        
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: type=sha

    - name: Init test environment
      id: test_resources
      run: |
        docker compose -f docker.yml -p shine-identity up -d
        echo "pg_host=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' shine-identity-postgres-1)" >> $GITHUB_OUTPUT
        echo "redis_host=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' shine-identity-redis-1)" >> $GITHUB_OUTPUT
        echo "::group::Create certificates"
        cd ../integration-test
        npm ci
        npm run mkcert
        echo "::endgroup::"
      working-directory: ./service
        
    - name: Docker build
      uses: docker/build-push-action@v4
      with:
        context: service
        target: test
        push: false
        load: true
        add-hosts: |
          postgres.mock-test.com:${{ steps.test_resources.outputs.pg_host }}
          redis.mock-test.com:${{ steps.test_resources.outputs.redis_host }}
        cache-from: type=gha,mode=max
        cache-to: type=gha,mode=max
        tags: ${{ env.IMAGE_NAME }}:test
        
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 web.test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 cloud.test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 mock-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 postgres.mock-test.com" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 redis.mock-test.com" | sudo tee -a /etc/hosts
    - name: Integration test
      run: |
        echo "::group::Starting service in the test environment"
        docker compose -f ../service/docker.yml -p shine-identity --profile test up -d
        echo "::endgroup::"
        echo "::group::Running test"
        npm run jest regression
        echo "::endgroup::"
      working-directory: ./integration-test

    - name: Log in to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build prod
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: service
        target: prod
        push: true
        # these setting are here to allow the reuse of the layer from the build step
        # without host parameters it would trigger a new build
        add-hosts: |
          postgres.mock-test.com:${{ steps.test_resources.outputs.pg_host }}
          redis.mock-test.com:${{ steps.test_resources.outputs.redis_host }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Publish Test Reports
      if: github.event_name != 'pull_request' || failure()
      uses: actions/upload-artifact@v3
      with:
        name: Test Reports
        path: | 
          ./integration-test/reports/
