name: Deploy Fly

on:
  workflow_run:
    workflows: [Master CI]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: actions/download-artifact@v3
        with:
          name: release-artifacts
          path: ./release
          
      - name: Init fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./release
