name: Deploy Fly

on: [workflow_dispatch]
    
  #workflow_run:
  #  workflows: [Master CI]
  #  types: [completed]
  #  branches: [master]
    
jobs:
  deploy:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Init fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Test fly
        run: flyctl apps list
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "release-artifacts"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/release-artifacts.zip`, Buffer.from(download.data));  

      - name: Unzip artifact
        run: unzip release-artifacts.zip

      - name: Deploy to fly
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
